### ISSUE TITLE
More Fake Addons

### ISSUE THREAD

**Issue by SkyBird1980** [sualfred/sualfreds-repo#2]
Please add following fake Addons to your Repo 👯‍♂️ 
     123Movies
    1Channel
    4K UHD
    Adryanlist
    Aftershock
    All Movies Stream
    Amigos
    Animeram
    Ares / Ares Wizard
    BaddAssMovies4U
    BBTS
    Beast
    Binky TV
    CartoonHD
    Cartoons8
    cCloud TV
    Cloudword
    Community Portal (The Community Portal)
    Daffys
    DexterTV
    Diesel
    DOCU-HUB
    Dreamcatcher
    Eliplex TV
    Entertainment Hub
    Exodus
    F4Mtester
    Falcon
    F.T.V.
    Film Dictator
    Free Streams
    HUB/TVADDONS/Xfinity Config Wizard
    HUB/TVADDONS/Xfinity 'fresh start'
    Genesis
    GoMovies
    GoTV
    Halow
    i4atv
    I Watch Online
    IceFilms
    Indian TV (OTT)
    Indigo
    IPTV Stalker (not to be confused with Stalker Middleware)
    IPTV Simple Client 2 (not to be confused with the original and official "IPTV Simple Client")
    iStream
    iVue TV
    iwannawatch
    J1nxPack (Jinx/J1nx Pack)
    Jango Music
    Jeckyll Hyde
    Kidsflix
    Kiss Anime
    Kodiland
    KodiUK TV Wizard
    LatestDude
    Marvin
    MashUp
    Mega Search
    MK Sports
    Modbro Video
    MoneySports
    Movie Hut
    Movie Night
    Movie25
    Movie4k
    MoviesHD
    Movies XK
    MovieStorm
    MuchMovies
    Mutts Nuts
    Navi-X
    Nemesis
    NLView
    OCW Reborn
    OneClickMoviez
    Online Movies Pro
    Operation Robocop
    Ororo TV (ororo.tv)
    Paragon
    Players Klub
    Plexus
    Phoenix
    Popcorn Time
    Prime Links
    Primewire
    Project Cypher
    ProjectFreeTV (Project Free TV)
    Pulsar
    Pyramid
    Quasar
    RapidBit
    Renegades TV
    Rlseries
    RobinHood Project
    Royal We (The Royal We)
    SALTS (S.A.L.T.S. - Stream all the Sources)
    Silent Hunter
    Soap Catchup
    Stallion
    Specto
    SpinzTV
    SportsAccess
    Sport-A-Holic
    SportsDevil
    StreamStorm TV
    StreamThis.tv
    SuperStreams
    SuperTV
    TARDIS
    TeeVee
    The Beast
    T-Killa
    ToonMania
    TVOnline
    UK Turk Playlists
    UK TV Now
    Vdubt25
    VortechTV
    Whitecream
    Wookie Wizard
    Xfinity Installer
    XMovies8
    Yify Movies
    Zem TV
    Zeta TV
    Zeus 

Why? 
More fun :D

**Comment by SkyBird1980** [comment]
a little bit fun if nobody understand it ... ;)

**Comment by MartijnKaijser** [comment]
+1 from a not to be named group ;)
